### ISSUE TITLE
Interested in merging this repo into the storybook organisation?

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook-adk#1]
Maybe we can move this repo over to the storybook organisation?

End-goal being to do easier cross-compatibility testing and having the entire storybook team help maintain this.

**Comment by UsulPro** [comment]
@ndelangen, great idea! I'll be happy if it helps in addon development and involves more mountainers 👍

**Comment by phantom0424** [comment]
please go on

**Comment by UsulPro** [comment]
Done!
